### PR TITLE
Silence pull request security warnings

### PR DESCRIPTION
**Pull request by marcransome**
Justification for rule exclusions:

- [AVD-AWS-0011](https://avd.aquasec.com/misconfig/aws/cloudfront/avd-aws-0011/) - the CloudFront origin is not a dynamic web application but an S3 bucket holding static resources that are distributed directly to user agents, meaning a WAF rule is likely to offer little additional protection
- [AVD-AWS-0013](https://avd.aquasec.com/misconfig/aws/cloudfront/avd-aws-0013/) - restricting the minimum TLS protocol version to `TLSv1.2_2021` is _only_ possible when not using the default CloudFront certificate and domain (`cloudfront.net`); there are currently no plans to adopt a custom domain, however this may be revisited at some future date, at which point the minimum TLS version may be increased and this rule exclusion removed
- [AVD-AWS-0132](https://avd.aquasec.com/misconfig/aws/s3/avd-aws-0132/) - all content stored in the S3 CDN bucket is distributed publicly via CHS services and Customer Managed Keys offer little advantage over S3-managed keys; the access logs bucket will be replaced in the near future with a shared bucket managed outside of this project

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: No IaC security warnings found

**Comment by ch-code-analysis** [comment]
CI: No IaC security warnings found

**Review by sienkin — APPROVED** [review]

**Pull request merged**
