### PR TITLE
Rework to support multiple CloudFront distributions

### PR DESCRIPTION
**Pull request by marcransome**
Additional environments to be added at a later date.

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No IaC security warnings found

**Comment by ch-code-analysis** [comment]
CI: No IaC security warnings found

**Comment by ch-code-analysis** [comment]
CI: No IaC security warnings found

**Comment by ch-code-analysis** [comment]
CI: No IaC security warnings found

**Review by sienkin — APPROVED** [review]

**Pull request merged**
